# Generated by Django 5.2.17 on 2026-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginVersuch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benutzername", models.CharField(max_length=150)),
                ("ip_adresse", models.CharField(max_length=45)),
                ("erfolg", models.BooleanField(default=False)),
                ("zeitpunkt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["benutzername", "ip_adresse", "zeitpunkt"],
                        name="api_loginve_benutze_3fd39f_idx",
                    )
                ],
            },
        ),
    ]
