# Generated by Django 5.2.17 on 2026-10-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modulrecht",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("artikel_lesen", "Artikel: lesen"),
                    ("artikel_schreiben", "Artikel: schreiben"),
                    ("lager_lesen", "Lager: lesen"),
                    ("lager_schreiben", "Lager: schreiben"),
                    ("kunden_lesen", "Kunden: lesen"),
                    ("kunden_schreiben", "Kunden: schreiben"),
                    ("lieferanten_lesen", "Lieferanten: lesen"),
                    ("lieferanten_schreiben", "Lieferanten: schreiben"),
                    ("angebote_lesen", "Angebote: lesen"),
                    ("angebote_schreiben", "Angebote: schreiben"),
                    ("auftraege_lesen", "Aufträge: lesen"),
                    ("auftraege_schreiben", "Aufträge: schreiben"),
                    ("rechnungen_lesen", "Rechnungen: lesen"),
                    ("rechnungen_schreiben", "Rechnungen: schreiben"),
                    ("abos_lesen", "Abonnements: lesen"),
                    ("abos_schreiben", "Abonnements: schreiben"),
                    ("kategorien_lesen", "Kategorien: lesen"),
                    ("kategorien_schreiben", "Kategorien: schreiben"),
                    ("personal_lesen", "Personal: lesen"),
                    ("personal_schreiben", "Personal: schreiben"),
                    ("einstellungen_lesen", "Einstellungen: lesen"),
                    ("einstellungen_schreiben", "Einstellungen: schreiben"),
                ],
                "verbose_name": "Modulrecht",
                "verbose_name_plural": "Modulrechte",
            },
        ),
    ]
