# Generated by Django 5.2.17 on 2026-10-02 05:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kunde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firma",
                    models.CharField(blank=True, max_length=150, verbose_name="Firma"),
                ),
                (
                    "vorname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vorname"
                    ),
                ),
                (
                    "nachname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nachname"
                    ),
                ),
                (
                    "strasse",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Straße & Nr."
                    ),
                ),
                (
                    "plz",
                    models.CharField(blank=True, max_length=20, verbose_name="PLZ"),
                ),
                (
                    "ort",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "land",
                    models.CharField(
                        blank=True,
                        default="Deutschland",
                        max_length=100,
                        verbose_name="Land",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, verbose_name="E-Mail"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "steuernummer",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Steuernummer"
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "kundennummer",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Kundennummer",
                    ),
                ),
                (
                    "ust_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="USt-IdNr."
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(blank=True, max_length=30, verbose_name="BIC"),
                ),
                (
                    "bank",
                    models.CharField(blank=True, max_length=100, verbose_name="Bank"),
                ),
                (
                    "zahlungsart",
                    models.CharField(
                        choices=[
                            ("ueberweisung", "Überweisung"),
                            ("lastschrift", "Lastschrift"),
                        ],
                        default="ueberweisung",
                        max_length=15,
                        verbose_name="Zahlungsmethode",
                    ),
                ),
                (
                    "steuerbefreit",
                    models.BooleanField(
                        default=False,
                        verbose_name="Kunde ist steuerbefreit (0 % MwSt.)",
                    ),
                ),
                (
                    "befreiungsgrund",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Befreiungsgrund"
                    ),
                ),
                ("geaendert", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kunde",
                "verbose_name_plural": "Kunden",
                "ordering": ["firma", "nachname"],
            },
        ),
        migrations.CreateModel(
            name="Lieferant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firma",
                    models.CharField(blank=True, max_length=150, verbose_name="Firma"),
                ),
                (
                    "vorname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vorname"
                    ),
                ),
                (
                    "nachname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nachname"
                    ),
                ),
                (
                    "strasse",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Straße & Nr."
                    ),
                ),
                (
                    "plz",
                    models.CharField(blank=True, max_length=20, verbose_name="PLZ"),
                ),
                (
                    "ort",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "land",
                    models.CharField(
                        blank=True,
                        default="Deutschland",
                        max_length=100,
                        verbose_name="Land",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, verbose_name="E-Mail"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "steuernummer",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Steuernummer"
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "lieferantennummer",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Lieferantennummer",
                    ),
                ),
                (
                    "kundennummer_beim_lieferanten",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Unsere Kundennummer beim Lieferanten",
                    ),
                ),
                (
                    "zahlungsart",
                    models.CharField(
                        choices=[
                            ("ueberweisung", "Überweisung"),
                            ("lastschrift", "Lastschrift"),
                            ("zentralreguliert", "Zentralreguliert"),
                        ],
                        default="ueberweisung",
                        max_length=20,
                        verbose_name="Zahlungsmethode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieferant",
                "verbose_name_plural": "Lieferanten",
                "ordering": ["firma", "nachname"],
            },
        ),
        migrations.CreateModel(
            name="Kategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "uebergeordnet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unterkategorien",
                        to="stammdaten.kategorie",
                        verbose_name="Übergeordnete Kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Artikel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artikelnummer",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Artikelnummer",
                    ),
                ),
                (
                    "ean",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="EAN",
                    ),
                ),
                (
                    "han",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="HAN (Herstellerartikelnummer)",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "beschreibung",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "einheit",
                    models.CharField(
                        default="Stk.", max_length=20, verbose_name="Einheit"
                    ),
                ),
                (
                    "einkaufspreis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Einkaufspreis (€)",
                    ),
                ),
                (
                    "verkaufspreis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Verkaufspreis (€, netto)",
                    ),
                ),
                (
                    "steuersatz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        max_digits=5,
                        verbose_name="MwSt.-Satz (%)",
                    ),
                ),
                (
                    "bestand",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Bestand",
                    ),
                ),
                (
                    "mindestbestand",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Mindestbestand",
                    ),
                ),
                (
                    "lagerfuehrung",
                    models.BooleanField(
                        default=True, verbose_name="Lagerbestand verwalten"
                    ),
                ),
                (
                    "seriennummern",
                    models.BooleanField(
                        default=False, verbose_name="Seriennummern erfassen"
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                ("geaendert", models.DateTimeField(auto_now=True)),
                (
                    "kategorien",
                    models.ManyToManyField(
                        blank=True,
                        related_name="artikel",
                        to="stammdaten.kategorie",
                        verbose_name="Kategorien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artikel",
                "verbose_name_plural": "Artikel",
                "ordering": ["-aktiv", "name"],
            },
        ),
        migrations.CreateModel(
            name="Ansprechpartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nachname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nachname"
                    ),
                ),
                (
                    "vorname",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vorname"
                    ),
                ),
                (
                    "firma",
                    models.CharField(blank=True, max_length=150, verbose_name="Firma"),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefonnummer"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, verbose_name="E-Mailadresse"
                    ),
                ),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ansprechpartner",
                        to="stammdaten.kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ansprechpartner",
                "verbose_name_plural": "Ansprechpartner",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ArtikelLieferant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lieferanten_artikelnummer",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Artikelnummer beim Lieferanten",
                    ),
                ),
                (
                    "hek",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Unser HEK (€)",
                    ),
                ),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lieferanten",
                        to="stammdaten.artikel",
                    ),
                ),
                (
                    "lieferant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artikel",
                        to="stammdaten.lieferant",
                        verbose_name="Lieferant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieferant eines Artikels",
                "verbose_name_plural": "Lieferanten eines Artikels",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artikel", "lieferant"),
                        name="eindeutig_artikel_lieferant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Preisoption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abrechnung",
                    models.CharField(
                        choices=[
                            ("einmalig", "Einmalig"),
                            ("monatlich", "Monatlich"),
                            ("jaehrlich", "Jährlich"),
                        ],
                        default="einmalig",
                        max_length=10,
                        verbose_name="Modell",
                    ),
                ),
                (
                    "preis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Preis (€)",
                    ),
                ),
                (
                    "mindestlaufzeit_monate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Mindestlaufzeit (Monate)"
                    ),
                ),
                (
                    "kuendigungsfrist_tage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kündigungsfrist (Tage)"
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("sortierung", models.PositiveIntegerField(default=0)),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preisoptionen",
                        to="stammdaten.artikel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preisoption",
                "verbose_name_plural": "Preisoptionen",
                "ordering": ["sortierung", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artikel", "abrechnung"),
                        name="eindeutig_option_je_modell",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Sonderpreis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[("fixed", "Fixpreis (€)"), ("percent", "Rabatt (%)")],
                        default="fixed",
                        max_length=10,
                        verbose_name="Art",
                    ),
                ),
                (
                    "wert",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Wert"
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sonderpreise",
                        to="stammdaten.artikel",
                    ),
                ),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sonderpreise",
                        to="stammdaten.kunde",
                        verbose_name="Kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sonderpreis",
                "verbose_name_plural": "Sonderpreise",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artikel", "kunde"),
                        name="eindeutig_sonderpreis_je_kunde",
                    )
                ],
            },
        ),
    ]
