# Generated by Django 5.2.17 on 2026-10-02 06:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stammdaten", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Angebot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nummer",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Datum"
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "netto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Netto",
                    ),
                ),
                (
                    "steuer",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="MwSt.",
                    ),
                ),
                (
                    "brutto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Brutto",
                    ),
                ),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "gueltig_bis",
                    models.DateField(blank=True, null=True, verbose_name="Gültig bis"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("versendet", "Versendet"),
                            ("angenommen", "Angenommen"),
                            ("abgelehnt", "Abgelehnt"),
                        ],
                        default="entwurf",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stammdaten.kunde",
                        verbose_name="Kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Angebot",
                "verbose_name_plural": "Angebote",
                "ordering": ["-erstellt", "-pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AngebotPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=1, verbose_name="Pos."),
                ),
                (
                    "artikelnummer",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Artikelnummer"
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(max_length=255, verbose_name="Beschreibung"),
                ),
                (
                    "einheit",
                    models.CharField(
                        default="Stk.", max_length=20, verbose_name="Einheit"
                    ),
                ),
                (
                    "menge",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="Menge"
                    ),
                ),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Einzelpreis (netto)",
                    ),
                ),
                (
                    "rabatt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Rabatt (%)",
                    ),
                ),
                (
                    "steuersatz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        max_digits=5,
                        verbose_name="MwSt. (%)",
                    ),
                ),
                (
                    "abrechnung",
                    models.CharField(
                        choices=[
                            ("einmalig", "Einmalig"),
                            ("monatlich", "Monatlich"),
                            ("jaehrlich", "Jährlich"),
                        ],
                        default="einmalig",
                        max_length=10,
                        verbose_name="Modell",
                    ),
                ),
                (
                    "angebot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="belege.angebot",
                    ),
                ),
                (
                    "artikel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stammdaten.artikel",
                        verbose_name="Artikel",
                    ),
                ),
                (
                    "preisoption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stammdaten.preisoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Angebotsposition",
                "verbose_name_plural": "Angebotspositionen",
                "ordering": ["position", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Auftrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nummer",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Datum"
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "netto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Netto",
                    ),
                ),
                (
                    "steuer",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="MwSt.",
                    ),
                ),
                (
                    "brutto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Brutto",
                    ),
                ),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("in_bearbeitung", "In Bearbeitung"),
                            ("unterschrieben", "Unterschrieben"),
                            ("abgeschlossen", "Abgeschlossen"),
                            ("storniert", "Storniert"),
                        ],
                        default="offen",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "unterschrift",
                    models.ImageField(
                        blank=True,
                        upload_to="unterschriften/",
                        verbose_name="Unterschrift",
                    ),
                ),
                ("unterschrieben_am", models.DateTimeField(blank=True, null=True)),
                (
                    "unterschrieben_von",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Unterschrieben von"
                    ),
                ),
                (
                    "client_uuid",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "angebot",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auftrag",
                        to="belege.angebot",
                        verbose_name="Angebot",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stammdaten.kunde",
                        verbose_name="Kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auftrag",
                "verbose_name_plural": "Aufträge",
                "ordering": ["-erstellt", "-pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Abo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zyklus",
                    models.CharField(
                        choices=[("monatlich", "Monatlich"), ("jaehrlich", "Jährlich")],
                        max_length=10,
                        verbose_name="Abrechnung",
                    ),
                ),
                (
                    "menge",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="Menge"
                    ),
                ),
                (
                    "preis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Preis je Zyklus (netto)",
                    ),
                ),
                ("beginn", models.DateField(verbose_name="Beginn")),
                (
                    "naechste_abrechnung",
                    models.DateField(verbose_name="Nächste Abrechnung"),
                ),
                ("ende", models.DateField(blank=True, null=True, verbose_name="Ende")),
                (
                    "mindestlaufzeit_monate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Mindestlaufzeit (Monate)"
                    ),
                ),
                (
                    "kuendigungsfrist_tage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Kündigungsfrist (Tage)"
                    ),
                ),
                (
                    "fruehestes_ende",
                    models.DateField(
                        blank=True, null=True, verbose_name="Frühestes Vertragsende"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktiv", "Aktiv"),
                            ("gekuendigt", "Gekündigt"),
                            ("beendet", "Beendet"),
                        ],
                        default="aktiv",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "kuendigung_eingang",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kündigung eingegangen am"
                    ),
                ),
                (
                    "kuendigung_wirksam",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kündigung wirksam zum"
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                ("geaendert", models.DateTimeField(auto_now=True)),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abos",
                        to="stammdaten.artikel",
                        verbose_name="Artikel",
                    ),
                ),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="abos",
                        to="stammdaten.kunde",
                        verbose_name="Kunde",
                    ),
                ),
                (
                    "preisoption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stammdaten.preisoption",
                    ),
                ),
                (
                    "auftrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abos",
                        to="belege.auftrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement",
                "verbose_name_plural": "Abonnements",
                "ordering": ["naechste_abrechnung", "pk"],
            },
        ),
        migrations.CreateModel(
            name="AuftragPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=1, verbose_name="Pos."),
                ),
                (
                    "artikelnummer",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Artikelnummer"
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(max_length=255, verbose_name="Beschreibung"),
                ),
                (
                    "einheit",
                    models.CharField(
                        default="Stk.", max_length=20, verbose_name="Einheit"
                    ),
                ),
                (
                    "menge",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="Menge"
                    ),
                ),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Einzelpreis (netto)",
                    ),
                ),
                (
                    "rabatt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Rabatt (%)",
                    ),
                ),
                (
                    "steuersatz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        max_digits=5,
                        verbose_name="MwSt. (%)",
                    ),
                ),
                (
                    "abrechnung",
                    models.CharField(
                        choices=[
                            ("einmalig", "Einmalig"),
                            ("monatlich", "Monatlich"),
                            ("jaehrlich", "Jährlich"),
                        ],
                        default="einmalig",
                        max_length=10,
                        verbose_name="Modell",
                    ),
                ),
                (
                    "client_uuid",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "artikel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stammdaten.artikel",
                        verbose_name="Artikel",
                    ),
                ),
                (
                    "auftrag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="belege.auftrag",
                    ),
                ),
                (
                    "preisoption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stammdaten.preisoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auftragsposition",
                "verbose_name_plural": "Auftragspositionen",
                "ordering": ["position", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Rechnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Nummer",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Datum"
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "netto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Netto",
                    ),
                ),
                (
                    "steuer",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="MwSt.",
                    ),
                ),
                (
                    "brutto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="Brutto",
                    ),
                ),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "leistungsdatum",
                    models.DateField(
                        blank=True, null=True, verbose_name="Leistungsdatum"
                    ),
                ),
                (
                    "zeitraum_von",
                    models.DateField(
                        blank=True, null=True, verbose_name="Leistungszeitraum von"
                    ),
                ),
                (
                    "zeitraum_bis",
                    models.DateField(
                        blank=True, null=True, verbose_name="Leistungszeitraum bis"
                    ),
                ),
                (
                    "faellig_am",
                    models.DateField(blank=True, null=True, verbose_name="Fällig bis"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("entwurf", "Entwurf"),
                            ("versendet", "Versendet"),
                            ("bezahlt", "Bezahlt"),
                            ("ueberfaellig", "Überfällig"),
                            ("storniert", "Storniert"),
                        ],
                        default="entwurf",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                ("lagerbuchung", models.BooleanField(default=True, editable=False)),
                (
                    "abo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechnungen",
                        to="belege.abo",
                        verbose_name="Abonnement",
                    ),
                ),
                (
                    "angebot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechnungen",
                        to="belege.angebot",
                    ),
                ),
                (
                    "auftrag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechnungen",
                        to="belege.auftrag",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kunde",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stammdaten.kunde",
                        verbose_name="Kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
                "ordering": ["-erstellt", "-pk"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="abo",
            name="ursprungsrechnung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="belege.rechnung",
                verbose_name="Ursprungsrechnung",
            ),
        ),
        migrations.CreateModel(
            name="RechnungPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=1, verbose_name="Pos."),
                ),
                (
                    "artikelnummer",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Artikelnummer"
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(max_length=255, verbose_name="Beschreibung"),
                ),
                (
                    "einheit",
                    models.CharField(
                        default="Stk.", max_length=20, verbose_name="Einheit"
                    ),
                ),
                (
                    "menge",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="Menge"
                    ),
                ),
                (
                    "einzelpreis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Einzelpreis (netto)",
                    ),
                ),
                (
                    "rabatt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Rabatt (%)",
                    ),
                ),
                (
                    "steuersatz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        max_digits=5,
                        verbose_name="MwSt. (%)",
                    ),
                ),
                (
                    "abrechnung",
                    models.CharField(
                        choices=[
                            ("einmalig", "Einmalig"),
                            ("monatlich", "Monatlich"),
                            ("jaehrlich", "Jährlich"),
                        ],
                        default="einmalig",
                        max_length=10,
                        verbose_name="Modell",
                    ),
                ),
                (
                    "artikel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stammdaten.artikel",
                        verbose_name="Artikel",
                    ),
                ),
                (
                    "preisoption",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stammdaten.preisoption",
                    ),
                ),
                (
                    "rechnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positionen",
                        to="belege.rechnung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnungsposition",
                "verbose_name_plural": "Rechnungspositionen",
                "ordering": ["position", "pk"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="rechnung",
            constraint=models.UniqueConstraint(
                fields=("abo", "zeitraum_von"),
                name="eindeutig_abo_rechnung_je_zeitraum",
            ),
        ),
    ]
