# Generated by Django 5.2.17 on 2026-10-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auftrag",
            name="geaendert",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
