# Generated by Django 5.2.17 on 2026-10-09 10:24

import django.db.models.deletion
import kalender.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kalender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Name"),
                ),
                (
                    "farbe",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hexwert, z. B. #3b82f6",
                        max_length=7,
                        verbose_name="Farbe",
                    ),
                ),
                (
                    "beschreibung",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Beschreibung"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalender",
                "verbose_name_plural": "Kalender",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KalenderZugang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schluessel",
                    models.CharField(
                        default=kalender.models.neuer_schluessel,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "benutzer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kalender_zugang",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalender-Zugang",
                "verbose_name_plural": "Kalender-Zugänge",
            },
        ),
        migrations.CreateModel(
            name="Termin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=150, verbose_name="Titel")),
                (
                    "ort",
                    models.CharField(blank=True, max_length=150, verbose_name="Ort"),
                ),
                (
                    "beschreibung",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "ganztaegig",
                    models.BooleanField(default=False, verbose_name="Ganztägig"),
                ),
                ("beginn", models.DateTimeField(verbose_name="Beginn")),
                ("ende", models.DateTimeField(verbose_name="Ende")),
                (
                    "uid",
                    models.CharField(
                        default=kalender.models.neue_uid,
                        editable=False,
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                ("geaendert", models.DateTimeField(auto_now=True)),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kalender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termine",
                        to="kalender.kalender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin",
                "verbose_name_plural": "Termine",
                "ordering": ["beginn", "pk"],
                "indexes": [
                    models.Index(
                        fields=["beginn", "ende"], name="kalender_te_beginn_2b3f9c_idx"
                    )
                ],
            },
        ),
    ]
