# Generated by Django 5.2.17 on 2026-10-09 10:28

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kalender", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalDavVerbindung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aktiv",
                    models.BooleanField(default=False, verbose_name="Abgleich aktiv"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Nextcloud: https://cloud.example.de (die Endung /remote.php/dav wird bei Bedarf ergänzt). Radicale: http://server:5232",
                        max_length=300,
                        verbose_name="Server-Adresse",
                    ),
                ),
                (
                    "benutzer",
                    models.CharField(
                        blank=True,
                        help_text="Dienstkonto, z. B. kybro-sync",
                        max_length=150,
                        verbose_name="Benutzer",
                    ),
                ),
                (
                    "passwort",
                    core.fields.VerschluesseltesTextFeld(
                        blank=True,
                        help_text="Bei Nextcloud ein App-Passwort verwenden.",
                        verbose_name="Passwort",
                    ),
                ),
                (
                    "tls_pruefen",
                    models.BooleanField(
                        default=True, verbose_name="TLS-Zertifikat prüfen"
                    ),
                ),
                (
                    "zuletzt_abgeglichen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zuletzt abgeglichen"
                    ),
                ),
                (
                    "letzter_status",
                    models.TextField(blank=True, verbose_name="Letztes Ergebnis"),
                ),
            ],
            options={
                "verbose_name": "CalDAV-Verbindung",
                "verbose_name_plural": "CalDAV-Verbindung",
            },
        ),
        migrations.CreateModel(
            name="Zuordnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quelle",
                    models.CharField(
                        help_text="k<ID>, urlaub oder anwesenheit",
                        max_length=20,
                        unique=True,
                        verbose_name="KYBRO-Kalender",
                    ),
                ),
                (
                    "ziel_url",
                    models.CharField(
                        max_length=500, verbose_name="Zielkalender (Adresse)"
                    ),
                ),
                (
                    "ziel_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Zielkalender"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zuordnung",
                "verbose_name_plural": "Zuordnungen",
                "ordering": ["quelle"],
            },
        ),
        migrations.CreateModel(
            name="SyncEintrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=120)),
                ("pruefsumme", models.CharField(max_length=64)),
                ("ende", models.DateField()),
                (
                    "zuordnung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eintraege",
                        to="kalender.zuordnung",
                    ),
                ),
            ],
            options={
                "unique_together": {("zuordnung", "uid")},
            },
        ),
    ]
