# Generated by Django 5.2.17 on 2026-10-02 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stammdaten", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lagerbewegung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("einlagerung", "Einlagerung"),
                            ("auslagerung", "Auslagerung"),
                            ("korrektur", "Korrektur"),
                            ("verkauf", "Verkauf"),
                        ],
                        max_length=15,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "menge",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Menge"
                    ),
                ),
                (
                    "bezug_typ",
                    models.CharField(blank=True, max_length=30, verbose_name="Bezug"),
                ),
                ("bezug_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "notiz",
                    models.CharField(blank=True, max_length=255, verbose_name="Notiz"),
                ),
                (
                    "erstellt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datum"),
                ),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bewegungen",
                        to="stammdaten.artikel",
                    ),
                ),
                (
                    "benutzer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lagerbewegung",
                "verbose_name_plural": "Lagerbewegungen",
                "ordering": ["-erstellt", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Seriennummer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nummer",
                    models.CharField(max_length=100, verbose_name="Seriennummer"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lager", "Lager"),
                            ("verkauft", "Verkauft"),
                            ("defekt", "Defekt"),
                        ],
                        default="lager",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notiz",
                    models.CharField(blank=True, max_length=255, verbose_name="Notiz"),
                ),
                ("verkauft_am", models.DateTimeField(blank=True, null=True)),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "artikel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seriennummern_liste",
                        to="stammdaten.artikel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seriennummer",
                "verbose_name_plural": "Seriennummern",
                "ordering": ["status", "-erstellt"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artikel", "nummer"),
                        name="eindeutig_seriennummer_je_artikel",
                    )
                ],
            },
        ),
    ]
