# Generated by Django 5.2.17 on 2026-10-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0001_initial"),
        ("lager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seriennummer",
            name="rechnung",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seriennummern",
                to="belege.rechnung",
            ),
        ),
    ]
