# Generated by Django 5.2.17 on 2026-10-05 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mitarbeiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personalnummer",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Personalnummer",
                    ),
                ),
                ("vorname", models.CharField(max_length=100, verbose_name="Vorname")),
                ("nachname", models.CharField(max_length=100, verbose_name="Nachname")),
                (
                    "geburtsdatum",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geburtsdatum"
                    ),
                ),
                (
                    "strasse",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "plz",
                    models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
                ),
                (
                    "ort",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Position"
                    ),
                ),
                (
                    "abteilung",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Abteilung"
                    ),
                ),
                (
                    "notfallkontakt_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Notfallkontakt"
                    ),
                ),
                (
                    "notfallkontakt_telefon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telefon Notfallkontakt"
                    ),
                ),
                (
                    "eintrittsdatum",
                    models.DateField(
                        blank=True, null=True, verbose_name="Eintrittsdatum"
                    ),
                ),
                (
                    "austrittsdatum",
                    models.DateField(
                        blank=True, null=True, verbose_name="Austrittsdatum"
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "benutzer",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional. Erlaubt dem Benutzer, eigene Zeiten und Urlaub zu sehen und Urlaub zu beantragen.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mitarbeiter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verknüpfter Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiter",
                "verbose_name_plural": "Mitarbeiter",
                "ordering": ["nachname", "vorname"],
            },
        ),
        migrations.CreateModel(
            name="Urlaubsantrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("von", models.DateField(verbose_name="Von")),
                ("bis", models.DateField(verbose_name="Bis")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("beantragt", "Beantragt"),
                            ("genehmigt", "Genehmigt"),
                            ("abgelehnt", "Abgelehnt"),
                            ("storniert", "Storniert"),
                        ],
                        default="beantragt",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bemerkung",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Bemerkung"
                    ),
                ),
                ("entschieden_am", models.DateTimeField(blank=True, null=True)),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "entschieden_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mitarbeiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urlaubsantraege",
                        to="personal.mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Urlaubsantrag",
                "verbose_name_plural": "Urlaubsanträge",
                "ordering": ["-von"],
            },
        ),
        migrations.CreateModel(
            name="Vertrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gueltig_ab", models.DateField(verbose_name="Gültig ab")),
                (
                    "gueltig_bis",
                    models.DateField(
                        blank=True,
                        help_text="Leer = unbefristet gültig.",
                        null=True,
                        verbose_name="Gültig bis",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("vollzeit", "Vollzeit"),
                            ("teilzeit", "Teilzeit"),
                            ("minijob", "Minijob"),
                            ("azubi", "Auszubildende/r"),
                            ("werkstudent", "Werkstudent/in"),
                            ("freiberuflich", "Freie Mitarbeit"),
                        ],
                        default="vollzeit",
                        max_length=20,
                        verbose_name="Beschäftigungsart",
                    ),
                ),
                (
                    "wochenstunden",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        max_digits=5,
                        verbose_name="Wochenstunden",
                    ),
                ),
                (
                    "arbeitstage",
                    models.CharField(
                        default="0,1,2,3,4", max_length=20, verbose_name="Arbeitstage"
                    ),
                ),
                (
                    "urlaubstage_pro_jahr",
                    models.DecimalField(
                        decimal_places=1,
                        default=30,
                        max_digits=5,
                        verbose_name="Urlaubstage pro Jahr",
                    ),
                ),
                (
                    "probezeit_ende",
                    models.DateField(
                        blank=True, null=True, verbose_name="Probezeit bis"
                    ),
                ),
                (
                    "befristet_bis",
                    models.DateField(
                        blank=True, null=True, verbose_name="Befristet bis"
                    ),
                ),
                (
                    "kuendigungsfrist",
                    models.CharField(
                        blank=True,
                        help_text="z. B. 4 Wochen zum Monatsende",
                        max_length=100,
                        verbose_name="Kündigungsfrist",
                    ),
                ),
                ("notizen", models.TextField(blank=True, verbose_name="Notizen")),
                (
                    "mitarbeiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vertraege",
                        to="personal.mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vertrag",
                "verbose_name_plural": "Verträge",
                "ordering": ["-gueltig_ab"],
            },
        ),
        migrations.CreateModel(
            name="Anwesenheit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(verbose_name="Datum")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("anwesend", "Anwesend"),
                            ("homeoffice", "Homeoffice"),
                            ("dienstreise", "Dienstreise"),
                            ("krank", "Krank"),
                            ("sonderurlaub", "Sonderurlaub"),
                            ("freizeitausgleich", "Freizeitausgleich"),
                        ],
                        default="anwesend",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("von", models.TimeField(blank=True, null=True, verbose_name="Kommen")),
                ("bis", models.TimeField(blank=True, null=True, verbose_name="Gehen")),
                (
                    "notiz",
                    models.CharField(blank=True, max_length=200, verbose_name="Notiz"),
                ),
                (
                    "mitarbeiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anwesenheiten",
                        to="personal.mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anwesenheit",
                "verbose_name_plural": "Anwesenheiten",
                "ordering": ["-datum"],
                "unique_together": {("mitarbeiter", "datum")},
            },
        ),
        migrations.CreateModel(
            name="Urlaubsjahr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.PositiveSmallIntegerField(verbose_name="Jahr")),
                (
                    "anspruch",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Leer = aus dem Vertrag berechnen (anteilig bei Eintritt im Jahr).",
                        max_digits=5,
                        null=True,
                        verbose_name="Anspruch (manuell)",
                    ),
                ),
                (
                    "uebertrag",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=5,
                        verbose_name="Übertrag aus Vorjahr",
                    ),
                ),
                (
                    "notiz",
                    models.CharField(blank=True, max_length=200, verbose_name="Notiz"),
                ),
                (
                    "mitarbeiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urlaubsjahre",
                        to="personal.mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Urlaubsjahr",
                "verbose_name_plural": "Urlaubsjahre",
                "ordering": ["-jahr"],
                "unique_together": {("mitarbeiter", "jahr")},
            },
        ),
    ]
