# Generated by Django 5.2.17 on 2026-10-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anwesenheit",
            name="status",
            field=models.CharField(
                choices=[
                    ("anwesend", "Anwesend"),
                    ("homeoffice", "Homeoffice"),
                    ("dienstreise", "Dienstreise"),
                    ("krank", "Krank"),
                    ("sonderurlaub", "Sonderurlaub"),
                    ("freizeitausgleich", "Freizeitausgleich"),
                    ("berufsschule", "Berufsschule"),
                    ("schulung", "Schulung"),
                ],
                default="anwesend",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
