# Generated by Django 5.2.17 on 2026-10-05 19:21

import django.core.validators
from django.db import migrations, models


def standard_sondertage(apps, schema_editor):
    Sondertag = apps.get_model("personal", "Sondertag")
    for name, tag, monat in (("Heiligabend", 24, 12), ("Silvester", 31, 12)):
        Sondertag.objects.create(name=name, tag=tag, monat=monat, urlaubsanteil=0.5)


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_anwesenheit_berufsschule_schulung"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalEinstellung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bundesland",
                    models.CharField(
                        blank=True,
                        help_text="Bestimmt die gesetzlichen Feiertage. Leer = keine gesetzlichen Feiertage.",
                        max_length=2,
                        verbose_name="Bundesland",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal-Einstellung",
                "verbose_name_plural": "Personal-Einstellungen",
            },
        ),
        migrations.CreateModel(
            name="Sondertag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bezeichnung")),
                (
                    "tag",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Tag",
                    ),
                ),
                (
                    "monat",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Monat",
                    ),
                ),
                (
                    "jahr",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leer = jedes Jahr.",
                        null=True,
                        verbose_name="Nur im Jahr",
                    ),
                ),
                (
                    "urlaubsanteil",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=2,
                        verbose_name="Urlaubsanteil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sondertag",
                "verbose_name_plural": "Sondertage",
                "ordering": ["monat", "tag", "jahr"],
            },
        ),
        migrations.RunPython(standard_sondertage, migrations.RunPython.noop),
    ]
