# Generated by Django 5.2.17 on 2026-10-07 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0003_einstellungen_sondertage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stundenkorrektur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(verbose_name="Datum")),
                (
                    "stunden",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Überstunden positiv, Fehlstunden negativ (z. B. -1,5). Dezimalstunden: 1,5 = 1 Std. 30 Min.",
                        max_digits=6,
                        verbose_name="Stunden",
                    ),
                ),
                (
                    "bemerkung",
                    models.CharField(max_length=300, verbose_name="Bemerkung"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("beantragt", "Beantragt"),
                            ("genehmigt", "Genehmigt"),
                            ("abgelehnt", "Abgelehnt"),
                            ("storniert", "Storniert"),
                        ],
                        default="beantragt",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                ("entschieden_am", models.DateTimeField(blank=True, null=True)),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
                (
                    "entschieden_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mitarbeiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stundenkorrekturen",
                        to="personal.mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Über-/Fehlstunden",
                "verbose_name_plural": "Über-/Fehlstunden",
                "ordering": ["-datum", "-pk"],
            },
        ),
    ]
