# Generated by Django 5.2.17 on 2026-10-02 06:02

import core.fields
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Firma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firmenname",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Firmenname"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="firma/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Logo",
                    ),
                ),
                (
                    "briefbogen",
                    models.FileField(
                        blank=True,
                        upload_to="firma/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "pdf"]
                            )
                        ],
                        verbose_name="Briefbogen (Hintergrund der PDFs)",
                    ),
                ),
                (
                    "strasse",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Straße & Nr."
                    ),
                ),
                (
                    "plz",
                    models.CharField(blank=True, max_length=20, verbose_name="PLZ"),
                ),
                (
                    "ort",
                    models.CharField(blank=True, max_length=100, verbose_name="Ort"),
                ),
                (
                    "land",
                    models.CharField(
                        blank=True,
                        default="Deutschland",
                        max_length=100,
                        verbose_name="Land",
                    ),
                ),
                (
                    "steuernummer",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Steuernummer"
                    ),
                ),
                (
                    "ust_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="USt-IdNr."
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
                ),
                (
                    "bic",
                    models.CharField(blank=True, max_length=30, verbose_name="BIC"),
                ),
                (
                    "bank",
                    models.CharField(blank=True, max_length=100, verbose_name="Bank"),
                ),
                (
                    "kontoinhaber",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Kontoinhaber"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=150, verbose_name="E-Mail"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "praefix_angebot",
                    models.CharField(
                        default="ANG-", max_length=20, verbose_name="Präfix Angebote"
                    ),
                ),
                (
                    "praefix_auftrag",
                    models.CharField(
                        default="AUF-", max_length=20, verbose_name="Präfix Aufträge"
                    ),
                ),
                (
                    "praefix_rechnung",
                    models.CharField(
                        default="RE-", max_length=20, verbose_name="Präfix Rechnungen"
                    ),
                ),
                (
                    "standard_steuersatz",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        max_digits=5,
                        verbose_name="Standard-MwSt.-Satz (%)",
                    ),
                ),
                (
                    "zahlungsziel_tage",
                    models.PositiveIntegerField(
                        default=14, verbose_name="Zahlungsziel (Tage)"
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="SMTP-Server"
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP-Port"),
                ),
                (
                    "smtp_verschluesselung",
                    models.CharField(
                        choices=[
                            ("none", "Keine"),
                            ("ssl", "SSL/TLS (meist Port 465)"),
                            ("tls", "STARTTLS (meist Port 587)"),
                        ],
                        default="tls",
                        max_length=4,
                        verbose_name="Verschlüsselung",
                    ),
                ),
                (
                    "smtp_benutzer",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="SMTP-Benutzer"
                    ),
                ),
                (
                    "smtp_passwort",
                    core.fields.VerschluesseltesTextFeld(
                        blank=True, verbose_name="SMTP-Passwort"
                    ),
                ),
                (
                    "smtp_absender_adresse",
                    models.EmailField(
                        blank=True, max_length=150, verbose_name="Absenderadresse"
                    ),
                ),
                (
                    "smtp_absender_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Absendername"
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma",
                "verbose_name_plural": "Firma",
            },
        ),
        migrations.CreateModel(
            name="Nummernkreis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("angebot", "Angebot"),
                            ("auftrag", "Auftrag"),
                            ("rechnung", "Rechnung"),
                        ],
                        max_length=10,
                    ),
                ),
                ("jahr", models.PositiveIntegerField()),
                ("naechste_nummer", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Nummernkreis",
                "verbose_name_plural": "Nummernkreise",
                "ordering": ["art", "-jahr"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("art", "jahr"), name="eindeutig_nummernkreis"
                    )
                ],
            },
        ),
    ]
