# Generated by Django 5.2.17 on 2026-10-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formulareinstellung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bereich", models.CharField(max_length=20, verbose_name="Bereich")),
                (
                    "schluessel",
                    models.CharField(max_length=50, verbose_name="Schlüssel"),
                ),
                ("wert", models.TextField(blank=True, verbose_name="Wert")),
            ],
            options={
                "verbose_name": "Formulareinstellung",
                "verbose_name_plural": "Formulareinstellungen",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bereich", "schluessel"),
                        name="eindeutig_formulareinstellung",
                    )
                ],
            },
        ),
    ]
