# Generated by Django 5.2.17 on 2026-10-02 06:18

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0002_formulareinstellung"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authentifizierung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modus",
                    models.CharField(
                        choices=[
                            ("local", "Nur lokale Datenbank"),
                            (
                                "ldap",
                                "Nur LDAP (lokale Administratoren nur im Notfall)",
                            ),
                            ("ldap_then_local", "LDAP vor lokaler Datenbank"),
                            ("local_then_ldap", "Lokale Datenbank vor LDAP"),
                        ],
                        default="local",
                        max_length=20,
                        verbose_name="Anmeldeverfahren",
                    ),
                ),
                (
                    "ldap_host",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="LDAP-Server"
                    ),
                ),
                (
                    "ldap_port",
                    models.PositiveIntegerField(default=389, verbose_name="Port"),
                ),
                (
                    "ldap_verschluesselung",
                    models.CharField(
                        choices=[
                            ("none", "Keine"),
                            ("starttls", "StartTLS"),
                            ("ldaps", "LDAPS"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Verschlüsselung",
                    ),
                ),
                (
                    "ldap_base_dn",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Base DN"
                    ),
                ),
                (
                    "ldap_bind_dn",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Bind-DN (Service-Account)",
                    ),
                ),
                (
                    "ldap_bind_passwort",
                    core.fields.VerschluesseltesTextFeld(
                        blank=True, verbose_name="Bind-Passwort"
                    ),
                ),
                (
                    "ldap_benutzerfilter",
                    models.CharField(
                        default="(uid=%s)",
                        max_length=255,
                        verbose_name="Benutzerfilter",
                    ),
                ),
                (
                    "ldap_namensattribut",
                    models.CharField(
                        default="cn", max_length=50, verbose_name="Attribut Anzeigename"
                    ),
                ),
                (
                    "ldap_mailattribut",
                    models.CharField(
                        default="mail", max_length=50, verbose_name="Attribut E-Mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Authentifizierung",
                "verbose_name_plural": "Authentifizierung",
            },
        ),
        migrations.CreateModel(
            name="Lizenz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referenz",
                    models.CharField(
                        max_length=150, verbose_name="Kunden-/Installationsreferenz"
                    ),
                ),
                ("gueltig_ab", models.DateField(verbose_name="Gültig ab")),
                (
                    "gueltig_bis",
                    models.DateField(
                        blank=True,
                        help_text="Leer = unbefristet.",
                        null=True,
                        verbose_name="Gültig bis",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("expired", "Abgelaufen"),
                            ("revoked", "Widerrufen"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "module",
                    models.JSONField(blank=True, default=list, verbose_name="Module"),
                ),
                ("erstellt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lizenz",
                "verbose_name_plural": "Lizenzen",
                "ordering": ["-gueltig_ab", "-pk"],
            },
        ),
    ]
