# Generated by Django 5.2.17 on 2026-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0003_authentifizierung_lizenz"),
    ]

    operations = [
        migrations.AddField(
            model_name="firma",
            name="betriebsmodus",
            field=models.CharField(
                choices=[("test", "Testbetrieb"), ("live", "Live-Betrieb")],
                default="test",
                max_length=4,
                verbose_name="Betriebsmodus",
            ),
        ),
    ]
