# Generated by Django 5.2.17 on 2026-10-05 11:39

import django.core.validators
from django.db import migrations, models


def logo_uebernehmen(apps, schema_editor):
    """Ein vorhandenes Firmenlogo wird als Bild-Element oben links übernommen (Höhe wie bisher ca. 20 mm)."""
    Firma = apps.get_model("einstellungen", "Firma")
    Element = apps.get_model("einstellungen", "BriefbogenElement")
    firma = Firma.objects.filter(pk=1).first()
    if firma and firma.logo:
        Element.objects.create(
            name="Logo", typ="bild", reihenfolge=0, x_mm=20, y_mm=8, breite_mm=50, hoehe_mm=20,
            vertikale_ausrichtung="oben", bild=firma.logo.name, seitenverhaeltnis_beibehalten=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0004_betriebsmodus"),
    ]

    operations = [
        migrations.CreateModel(
            name="BriefbogenElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Nur zur Wiedererkennung in der Liste, erscheint nicht im PDF.",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[("bild", "Bild"), ("textbox", "Textblock")],
                        default="bild",
                        max_length=10,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "reihenfolge",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Bei Überlappung liegen höhere Werte weiter oben.",
                        verbose_name="Reihenfolge",
                    ),
                ),
                (
                    "x_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Abstand vom linken Blattrand.",
                        max_digits=6,
                        verbose_name="X-Position (mm)",
                    ),
                ),
                (
                    "y_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Abstand von der Papieroberkante. Welche Kante des Elements das ist, bestimmt „Vertikale Ausrichtung“.",
                        max_digits=6,
                        verbose_name="Y-Position (mm)",
                    ),
                ),
                (
                    "breite_mm",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Breite (mm)"
                    ),
                ),
                (
                    "hoehe_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional: leer = automatisch (Bild nach Seitenverhältnis, Text nach Umfang).",
                        max_digits=6,
                        null=True,
                        verbose_name="Höhe (mm)",
                    ),
                ),
                (
                    "vertikale_ausrichtung",
                    models.CharField(
                        choices=[("oben", "Oben"), ("unten", "Unten")],
                        default="oben",
                        help_text="Oben: Y ist die Oberkante, Inhalt wächst nach unten. Unten: Y ist die Unterkante, Inhalt wächst nach oben (z. B. für bündige Fußzeilenblöcke).",
                        max_length=5,
                        verbose_name="Vertikale Ausrichtung",
                    ),
                ),
                (
                    "bild",
                    models.ImageField(
                        blank=True,
                        upload_to="briefbogen/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            )
                        ],
                        verbose_name="Bild",
                    ),
                ),
                (
                    "seitenverhaeltnis_beibehalten",
                    models.BooleanField(
                        default=True, verbose_name="Seitenverhältnis beibehalten"
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Text")),
                (
                    "schriftart",
                    models.CharField(
                        blank=True,
                        default="Helvetica",
                        max_length=30,
                        verbose_name="Schriftart",
                    ),
                ),
                (
                    "schriftgroesse",
                    models.PositiveIntegerField(
                        blank=True,
                        default=10,
                        null=True,
                        verbose_name="Schriftgröße (pt)",
                    ),
                ),
                (
                    "schriftfarbe",
                    models.CharField(
                        blank=True,
                        help_text="Leer = Standardfarbe (dunkelgrau).",
                        max_length=7,
                        verbose_name="Schriftfarbe",
                    ),
                ),
                (
                    "ausrichtung",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("links", "Links"),
                            ("mitte", "Zentriert"),
                            ("rechts", "Rechts"),
                        ],
                        default="links",
                        max_length=6,
                        verbose_name="Ausrichtung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Briefbogen-Element",
                "verbose_name_plural": "Briefbogen-Elemente",
                "ordering": ["reihenfolge", "pk"],
            },
        ),
        migrations.RunPython(logo_uebernehmen, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="firma",
            name="briefbogen",
        ),
        migrations.RemoveField(
            model_name="firma",
            name="logo",
        ),
    ]
