# Generated by Django 5.2.17 on 2026-10-06 05:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0005_briefbogen"),
    ]

    operations = [
        migrations.AddField(
            model_name="briefbogenelement",
            name="zeilenhoehe",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("1.15"),
                help_text="Zeilenabstand als Vielfaches der Schriftgröße: 1,0 = eng, 1,15 = Standard, 1,5 = weit.",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.8),
                    django.core.validators.MaxValueValidator(3),
                ],
                verbose_name="Zeilenhöhe (Faktor)",
            ),
        ),
    ]
