# Generated by Django 5.2.17 on 2026-10-07 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0006_briefbogen_zeilenhoehe"),
    ]

    operations = [
        migrations.AddField(
            model_name="firma",
            name="portal_logo",
            field=models.ImageField(
                blank=True,
                help_text="Erscheint über „KYBRO“ auf der Anmeldeseite (PNG oder JPG, am besten mit transparentem oder weißem Hintergrund).",
                upload_to="portal/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    )
                ],
                verbose_name="Logo für die Anmeldeseite",
            ),
        ),
    ]
