# Generated by Django 5.2.17 on 2026-10-07 05:39

import django.core.validators
import einstellungen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0007_portal_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firma",
            name="portal_logo",
            field=models.FileField(
                blank=True,
                help_text="Erscheint über „KYBRO“ auf der Anmeldeseite (PNG, JPG oder SVG; SVG ohne Skripte).",
                upload_to="portal/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "svg"]
                    ),
                    einstellungen.models.logo_pruefen,
                ],
                verbose_name="Logo für die Anmeldeseite",
            ),
        ),
    ]
