# Generated by Django 5.2.17 on 2026-10-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("einstellungen", "0008_portal_logo_svg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firma",
            name="portal_logo",
        ),
    ]
